### ISSUE TITLE
Git binary error

### ISSUE THREAD

**Issue by Liandriz** [cweiske/phorkie#33]
Hi, got this error on list page : "Guessing path to git binary is failed. You must specify path to git binary yourself.", any hint about it please? Git is installed, available in path, and can't get where in the phorkie config modify it?  

Thanks for help.

**Comment by cweiske** [comment]
It's the PEAR package `VersionControl_Git` that throws this error. It uses pear-core-minimal's `System.php` `which` method to find `git`.

The question is if your web server makes the `PATH` variable available or not.
Create a file called `phpinfo.php` with this content:

```
<?php
phpinfo();
```

Load it in your browser, and look for the list of environment variables. Is the PATH in there? If yes, does it contain the directory that `git` is in?

If you answered one of the questions with "no", open `data/config.php` and add (and adjust):

```
putenv("PATH=/usr/bin");
```

Does that help?

**Comment by Liandriz** [comment]
Thanks, PHP-FPM didn't get the PATH, and manually adding it to config.php works.  
Another thing, will you add some simple login, or is OpenID mandatory?

**Comment by cweiske** [comment]
I might add IndieAuth one day, but there will be no own user management.

**Comment by Liandriz** [comment]
Thanks will wait for it!
